# Generated by Django 3.0.6 on 2020-08-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='url',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
